"""empty message

Revision ID: 1a857bc4b970
Revises: 52c93b4019f0
Create Date: 2020-05-25 12:02:57.543182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a857bc4b970'
down_revision = '52c93b4019f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('bgcolorhex', sa.String(length=6), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('label', 'bgcolorhex')
    # ### end Alembic commands ###
