"""Added validated field to UA table

Revision ID: 2447364e2399
Revises: 57491872cbad
Create Date: 2021-04-02 13:49:28.460220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2447364e2399'
down_revision = '57491872cbad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_annotation', sa.Column('validated', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_annotation', 'validated')
    # ### end Alembic commands ###
