"""Added exception field to Task

Revision ID: 2a340de12c23
Revises: f703c7265e90
Create Date: 2021-01-11 18:03:23.534191

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a340de12c23'
down_revision = 'f703c7265e90'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('exception', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'exception')
    # ### end Alembic commands ###
