"""Multi annotation support

Revision ID: 3936f1de83fa
Revises: 88bd75fea49e
Create Date: 2020-04-19 10:51:19.920114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3936f1de83fa'
down_revision = '88bd75fea49e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('annotation',
    sa.Column('tweet_id', sa.Integer(), nullable=False),
    sa.Column('appuser_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('labels', sa.PickleType(), nullable=True),
    sa.Column('highlights', sa.PickleType(), nullable=True),
    sa.Column('tags', sa.PickleType(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['appuser_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['tweet_id'], ['tweet.id'], ),
    sa.PrimaryKeyConstraint('tweet_id', 'appuser_id', 'timestamp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('annotation')
    # ### end Alembic commands ###
