"""empty message

Revision ID: 52c93b4019f0
Revises: 3936f1de83fa
Create Date: 2020-05-12 12:45:13.903087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52c93b4019f0'
down_revision = '3936f1de83fa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('multiple', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('label', 'multiple')
    # ### end Alembic commands ###
