"""empty message

Revision ID: 7a8648c8b956
Revises: 113842e1ad28
Create Date: 2020-01-23 12:34:34.609540

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8648c8b956'
down_revision = '113842e1ad28'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('app_user', sa.Column('authorized', sa.Boolean(), nullable=False))
    op.add_column('app_user', sa.Column('permission_level', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('app_user', 'permission_level')
    op.drop_column('app_user', 'authorized')
    # ### end Alembic commands ###
