"""empty message

Revision ID: 88bd75fea49e
Revises: 7a8648c8b956
Create Date: 2020-01-24 16:25:22.036045

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88bd75fea49e'
down_revision = '7a8648c8b956'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tweet', sa.Column('is_retweet', sa.Boolean(), nullable=True))
    op.add_column('tweet', sa.Column('parent_tweet', sa.String(length=19), nullable=True))
    op.create_unique_constraint(None, 'tweet', ['parent_tweet'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tweet', type_='unique')
    op.drop_column('tweet', 'parent_tweet')
    op.drop_column('tweet', 'is_retweet')
    # ### end Alembic commands ###
