"""Added order to labels

Revision ID: ad2acb6301af
Revises: 4de5ff2b1f2e
Create Date: 2020-07-01 17:48:11.787856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ad2acb6301af'
down_revision = '4de5ff2b1f2e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('order', sa.Float(), nullable=False))
    op.create_index(op.f('ix_label_order'), 'label', ['order'], unique=False)
    op.execute('UPDATE "label" SET "order"="id"')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_label_order'), table_name='label')
    op.drop_column('label', 'order')
    # ### end Alembic commands ###
