"""Added VideoAnnotations

Revision ID: b16aeb96aa4c
Revises: 2447364e2399
Create Date: 2021-04-22 19:49:18.523599

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b16aeb96aa4c'
down_revision = '2447364e2399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('video_label',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('order', sa.Float(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('values', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_video_label_order'), 'video_label', ['order'], unique=False)
    op.create_table('video_annotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('labels', sa.PickleType(), nullable=True),
    sa.Column('appuser_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appuser_id'], ['app_user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('video_annotation')
    op.drop_index(op.f('ix_video_label_order'), table_name='video_label')
    op.drop_table('video_label')
    # ### end Alembic commands ###
