"""UserAnnotation for property expansion

Revision ID: c174a09daa49
Revises: e5e6577330a5
Create Date: 2020-06-17 12:31:58.739413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c174a09daa49'
down_revision = 'e5e6577330a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_annotation',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('appuser_id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('extended_labels', sa.PickleType(), nullable=True),
    sa.ForeignKeyConstraint(['appuser_id'], ['app_user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'appuser_id', 'timestamp')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_annotation')
    # ### end Alembic commands ###
