"""Added revision capabilities to UserAnnotation

Revision ID: c3d10b530b8c
Revises: ad2acb6301af
Create Date: 2020-07-01 20:59:34.969422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3d10b530b8c'
down_revision = 'ad2acb6301af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_annotation', sa.Column('decision', sa.Integer(), nullable=True))
    op.add_column('user_annotation', sa.Column('reviewed', sa.Boolean(), nullable=False))
    op.add_column('user_annotation', sa.Column('reviewed_by', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user_annotation', 'app_user', ['reviewed_by'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_annotation', type_='foreignkey')
    op.drop_column('user_annotation', 'reviewed_by')
    op.drop_column('user_annotation', 'reviewed')
    op.drop_column('user_annotation', 'decision')
    # ### end Alembic commands ###
