"""empty message

Revision ID: c768b780ba75
Revises: 1a857bc4b970
Create Date: 2020-05-29 11:46:40.622562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c768b780ba75'
down_revision = '1a857bc4b970'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('label', sa.Column('kind', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('label', 'kind')
    # ### end Alembic commands ###
