"""Added videoname to V VideoAnnotation

Revision ID: e15849bb1dff
Revises: b16aeb96aa4c
Create Date: 2021-04-22 22:16:47.296545

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e15849bb1dff'
down_revision = 'b16aeb96aa4c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('video_annotation', sa.Column('video', sa.String(length=34), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video_annotation', 'video')
    # ### end Alembic commands ###
