"""empty message

Revision ID: e5e6577330a5
Revises: 9cf172078b82
Create Date: 2020-06-10 14:59:30.336454

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5e6577330a5'
down_revision = '9cf172078b82'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('parent_tweet', table_name='tweet')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('parent_tweet', 'tweet', ['parent_tweet'], unique=True)
    # ### end Alembic commands ###
